# Main configuration for the tool

api_url: 'https://beta-engine.energytransitionmodel.com/api/v3/scenarios/'

# Default failsafe
scenario:
  id: 2162987 # II3050 nationale sturing


output_folder: 'output'
# output_format: csv, of combined_csv, of als stream, als dataframe
